# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GEmojiPickerDemo (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GEmojiPickerDemo (iOS)
pod 'GEmojiPicker'
end

target 'GEmojiPickerDemo (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GEmojiPickerDemo (macOS)
pod 'GEmojiPicker'
end
